version: '3.4'

services:
  catalogdb:
    image: mongo
  
  basketdb:
    image: redis:alpine
  
  pgadmin:
    image: dpage/pgadmin4
  
  discountdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    extra_hosts:
      - "localhost:192.168.65.2"
 
  rabbitmq:
    image: rabbitmq:3-management-alpine

  catalog.api:
    image: anv89/micros:catalogApi
    
  discount.grpc:
    image: discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
    
  basket.api:
    image: anv89/micros:basketApi
  
  ordering.api:
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
  
  ocelotapigw:
    image: ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile

  shopping.aggregator:
    image: shoppingaggregator
    build:
      context: .
      dockerfile: ApiGateways/Shopping.Aggregator/Dockerfile

  ecartmicros:
    image: ecartmicros
    build:
      context: .
      dockerfile: WebApps/AspnetRunBasics/Dockerfile      

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
  elasticsearch-data: